**Loading the Dataset**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('drug200.csv')

In [ ]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
df.shape

(200, 6)

In [ ]:
df.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


**Data Preprocessing**

In [ ]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [ ]:
df["BP"].value_counts()

BP
HIGH      77
LOW       64
NORMAL    59
Name: count, dtype: int64

In [ ]:
df["Drug"].value_counts()

Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
df.Sex= le.fit_transform(df.Sex)
df.BP = le.fit_transform(df.BP)
df.Cholesterol = le.fit_transform(df.Cholesterol)
df.Drug = le.fit_transform(df.Drug)

**Splitting into Independent and Dependent Variables**

In [ ]:
x = df.drop("Drug",axis=1).values
y= df["Drug"].values

**Scaling features**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
s = StandardScaler()
x_scaled = s.fit_transform(x)

**Splitting the Dataset into Training and Testing**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

**Converting features into Float**

In [ ]:
from tensorflow import keras

In [ ]:
Y_train = keras.utils.to_categorical(y_train)
Y_test = keras.utils.to_categorical(y_test)

**ANN Model**

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(12, input_dim = 5,activation = 'relu'))
model.add(Dense(24, activation = 'relu'))
model.add(Dense(36, activation = 'relu'))
model.add(Dense(5, activation = "softmax"))

In [ ]:
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 12)                72        
                                                                 
 dense_9 (Dense)             (None, 24)                312       
                                                                 
 dense_10 (Dense)            (None, 36)                900       
                                                                 
 dense_11 (Dense)            (None, 5)                 185       
                                                                 
Total params: 1469 (5.74 KB)
Trainable params: 1469 (5.74 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss = "categorical_crossentropy",optimizer = 'adam', metrics = ["accuracy"])

In [ ]:
model.fit(x_train,Y_train, batch_size=10, epochs=20)

Epoch 1/20
16/16 [==============================] - 1s 2ms/step - loss: 4.1771 - accuracy: 0.3313
Epoch 2/20
16/16 [==============================] - 0s 3ms/step - loss: 2.1117 - accuracy: 0.4688
Epoch 3/20
16/16 [==============================] - 0s 2ms/step - loss: 1.2558 - accuracy: 0.5625
Epoch 4/20
16/16 [==============================] - 0s 2ms/step - loss: 1.1513 - accuracy: 0.5500
Epoch 5/20
16/16 [==============================] - 0s 3ms/step - loss: 1.0840 - accuracy: 0.5813
Epoch 6/20
16/16 [==============================] - 0s 2ms/step - loss: 1.0638 - accuracy: 0.5312
Epoch 7/20
16/16 [==============================] - 0s 2ms/step - loss: 1.0330 - accuracy: 0.5688
Epoch 8/20
16/16 [==============================] - 0s 2ms/step - loss: 1.0098 - accuracy: 0.5813
Epoch 9/20
16/16 [==============================] - 0s 3ms/step - loss: 0.9975 - accuracy: 0.5938
Epoch 10/20
16/16 [==============================] - 0s 3ms/step - loss: 1.0155 - accuracy: 0.5688
Epoch 11/20
16/16 [

In [ ]:
loss, accuracy = model.evaluate(x_test, Y_test)
print("Accuracy is:", accuracy*100)

2/2 [==============================] - 0s 9ms/step - loss: 0.9991 - accuracy: 0.5250
Accuracy is: 52.49999761581421


In [ ]:
y_pred = model.predict(x_test)
y_pred

2/2 [==============================] - 0s 5ms/step


array([[3.18085968e-01, 1.48937717e-01, 1.17932983e-01, 1.16559915e-01,
        2.98483402e-01],
       [9.52056706e-01, 1.70343667e-02, 6.91835210e-03, 1.83408968e-02,
        5.64969424e-03],
       [3.50795209e-01, 1.28880605e-01, 8.02021995e-02, 1.30043566e-01,
        3.10078353e-01],
       [9.83260125e-02, 1.25540912e-01, 2.77679175e-01, 9.04041231e-02,
        4.08049792e-01],
       [9.98409927e-01, 7.09397544e-04, 1.06311600e-04, 4.67075413e-04,
        3.07458249e-04],
       [7.27056444e-01, 9.47167873e-02, 3.35831568e-02, 4.03522626e-02,
        1.04291312e-01],
       [9.97821748e-01, 8.73040117e-04, 2.61221052e-04, 9.66765510e-04,
        7.71254636e-05],
       [5.58240533e-01, 8.47646669e-02, 4.06140052e-02, 8.12892467e-02,
        2.35091582e-01],
       [3.52873147e-01, 1.98934853e-01, 1.38855711e-01, 8.29437822e-02,
        2.26392612e-01],
       [1.92118883e-02, 7.49831796e-02, 3.50471556e-01, 6.19730763e-02,
        4.93360281e-01],
       [6.26384258e-01, 1.1807

**Random Data Creation**

In [ ]:
num_sample = 5
random_input = np.random.rand(num_sample, x_train.shape[1])
random_input_scaled= s.transform(random_input)

**Prediction using Random Data**

In [ ]:
prediction = model.predict(random_input_scaled)

1/1 [==============================] - 0s 24ms/step


In [ ]:
predicted_drug = [np.argmax(pred) for pred in prediction]

In [ ]:
drug_mapping = {0:"DrugA",1:"DrugB", 2:"DrugC", 3:"DrugX", 4:"DrugY"}
predicted_drugs_names = [drug_mapping[pred] for pred in predicted_drug]

In [ ]:
print("Random Input data:")
print(random_input)
print("\nPredicted Drugs:")
print(predicted_drugs_names)

Random Input data:
[[0.07111275 0.62438842 0.0436479  0.70540923 0.25914757]
 [0.8461331  0.04242611 0.13948036 0.11214466 0.78873539]
 [0.78510469 0.16169202 0.54754381 0.66756115 0.71178304]
 [0.66670359 0.46480454 0.85594121 0.64771563 0.56926479]
 [0.97994685 0.38329685 0.17188211 0.36464032 0.61189519]]

Predicted Drugs:
['DrugB', 'DrugB', 'DrugB', 'DrugB', 'DrugB']
